### ISSUE TITLE
Navbar CSS is broken on Archive.org

### ISSUE THREAD

**Issue by rchrd2** [internetarchive/bookreader#177]
**Description**

The navbar appears correct in this bookreader repo, but on archive.org there is a visual bug. 

Screenshot of broken navbar: 

<img width="906" alt="Screen Shot 2019-10-31 at 9 37 42 PM" src="https://user-images.githubusercontent.com/182479/68002609-e86e2480-fc26-11e9-8f23-ff97713a2aec.png">

**Expectation**

Screenshot of correct navbar:

<img width="812" alt="Screen Shot 2019-10-31 at 9 36 47 PM" src="https://user-images.githubusercontent.com/182479/68002626-f8860400-fc26-11e9-9f88-0e07bcf673b4.png">

**Proposal & Constraints**

I going to try to fix this issue, but I found that BookReader itself is not broken, and the issue is only on archive.org.

There must be some conflicting CSS on archive.org that is breaking this.

**Comment by shaneriley** [comment]
I've been staring at this issue for over a month. It's due to an update to jQuery UI where we just grabbed their default styles and didn't check for regressions. Should just involve a few properties being reset. If you get to it before we do, let us know in a comment what selectors and properties to override and we'll integrate them into Petabox.

**Comment by rchrd2** [comment]
Was jQuery UI updated on archive.org? What version? I wonder if the same version should be upgraded in the BookReader repo, to keep the two in sync.

**Comment by shaneriley** [comment]
We're now on 1.12.1
